### ISSUE TITLE
CORS doesn't work for POST

### ISSUE THREAD

**Issue by eshikerya** [architect/architect-5#2]
In case web site and api working on different domains, even ports, we need CORS enabled.
In my case I have site on example.com and API created with ARC on api.example.com

Browser failed to go through preflight procedure, which mean successful OPTION request with Access-Control-Allow-Origin header set. AWS APIGateway give 500 "Internal server error" for any OPTION request with current configuration.

In current configuration I have .arc-config in folder with ```cors``` under ```@http```section, 
```javascript
    return {
        cors: true,
        status: 201,
        headers: {
            'Access-Control-Allow-Origin': '*',
            'Content-Type': 'application/json; charset=utf8',
        },
        body: JSON.stringify(body)
    };
```
and no way to get this working

**Steps to reproduce**
1. create new arc project
2. add post lambda handler
3. add config file and correct response
4. deploy to aws
5. test with ```curl -H "Origin: http://example.com" -H "Access-Control-Request-Method: OPTIONS" -H "Access-Control-Request-Headers: X-Requested-With" -X OPTIONS --verbose https://<your-api-entrypoint>```

**Expected behavior**
should return code 200 with ```Access-Control-Allow-Origin```header set from .arc-config file

**Comment by eshikerya** [comment]
sounds like [here](https://github.com/awslabs/aws-sam-cli/issues/323) the solution for configuration, in ```sam.json``` generated by ```arc-package``` I saw nothing about OPTIONS request

**Comment by eshikerya** [comment]
sounds like arc@6 have the way to solve it

**Comment by ryanblock** [comment]
Sorry to have missed this, I think you posted the issue in the wrong repo and we've been working like mad to get Arc 6 out. I don't understand your steps to reproduce, but I'll take the issue over there where you responded in https://github.com/architect/architect/issues/285
